version: "3.9"
services:
  web:
    # This builds the parent folder, but from this folder (yml still needs to be run here)
    build:
        context: ..
        dockerfile: ./src/Dockerfile
    ports:
      # why is this 3000? not sure but it works
      - "8000:3000"
