# A GitHub Action to get the latest commit that passed all checks.
# Fails when you need to manually merge, not sure if it's automatable

name: Merge latest green commit from true head into green head
on:
  push: # a merged PR always results in a push
    branches:
      - true-head
jobs:
  green-head-test:
    name: Check for green head
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: true-head branch checkout
        run: git fetch --all --unshallow && git checkout true-head

      - name: Run Docker container
        run: docker compose up -d --build
        working-directory: ./src

      - name: Remove __init__ in container
        run: docker exec src-web-1 rm __init__.py

      - name: Run end-to-end tests in container
        run: docker exec -w /code/testing/end_to_end_tests src-web-1 pytest

      - name: Set identity to Berwin
        run: git config --global user.email "blan@olin.edu" && git config --global user.name "Berwin Lan"

      - name: Merge into green-head if tests pass
        run: if [[ $? -eq 0 ]]; then git checkout green-head && git pull && git merge true-head && git push; fi

      - name: Shutdown container
        if: always()
        run: docker compose down
        working-directory: ./src
