# A GitHub Action to get the latest commit that passed all checks.

name: Check for green head
on:
  push: # a merged PR always results in a push
    branches:
      - true-head
jobs:
  green-head-test:
    name: Check for green head
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Install Python and Pytest
        run: sudo apt install python3 && pip install pytest

      - name: true-head branch checkout
        run: git fetch --all --unshallow && git checkout true-head

      - name: Run end-to-end test on true head
        working-directory: ./testing/end_to_end_tests
        run: pytest # returns 0 exit code if all tests pass

      - name: Merge into main if tests pass
        run: if [[ $? -eq 0 ]]; then git checkout green-head && git pull && git merge true-head && git push; fi
