name: Integration Tests
on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - true-head
jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install python3-pip && pip install -r requirements.txt
      - name: Switch Branch
        run: git checkout ${{ github.event.payload.pull_request.base }}
      - name: Run Tests
        id: run_tests
        run: ls && PYTHONPATH=. pytest ./testing/integration_tests/*.py
